---
- name: "gitlab: git_clone"
  include_role:
    name: "git"

- name: "gitlab: load spec file in 'tower_spec'"
  include_vars:
    file: "{{ git_store }}/.tower.yaml"
    name: "tower_spec"

- name: "gitlab: Launch Pipeline"
  run_once: true
  tower_workflow_launch:
    name: "{{ pipeline.name }}"
  loop: "{{ tower_spec.pipelines | selectattr('on', tower_webhook_payload.object_kind) | default([]) }}"
  loop_control:
    loop_var: "pipeline"
