---
- name: "git_clone: Create temporary folder"
  run_once: true
  tempfile:
    state: directory
    suffix: git_tempfile
  register: r_git_tempfile

- name: "git_clone: Set git_store"
  set_fact:
    git_store: "{{ r_tempfile_tower_import.path }}"

- name: "git_clone: Generate key_file"
  run_once: true
  blockinfile:
    block: "{{ git_deploy_key }}"
    path: "{{ git_deploy_key_file }}"
    mode: 0600
    create: true

- name: "git_clone: Clone repository"
  run_once: true
  git:
    accept_hostkey: true
    repo: "{{ git_url }}"
    dest: "{{ git_store }}"
    version: "{{ git_branch }}"
    key_file: "{{ git_key_file | default(omit) }}"
